# Generated by Django 3.0.6 on 2020-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='test', upload_to='img'),
            preserve_default=False,
        ),
    ]
